#log
logging:
  config: classpath:logback.xml
  level: debug

#server
server:
  port: 8999
  servlet-path: /aries-base
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: ./logs
      pattern: "%{X-Forwarded-For}i %a %{X-B3-TraceId}i %t %m %U %s %b %D"
      rename-on-rotate: true
      suffix: .log
      prefix: access
      rotate: true
      buffered: false
      file-date-format: yyyy-MM-dd

#admin
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://47.97.163.100:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      management.context-path: ${server.servlet-path}
    health-check-url-path: ${server.servlet-path}/health

#graceful quit
endpoints:
  shutdown:
    enabled: true
    sensitive: false

#rpc retry
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 25000
  threadpool:
      default:
        coreSize: 500

ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 1000
  #false to only allow get method to retry
  OkToRetryOnAllOperations: true
    # Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 2
    # Max number of retries on the same server (excluding the first try)
  MaxAutoRetries: 0
    # Interval to refresh the server list from the source
  ServerListRefreshInterval: 20000
  retryableStatusCodes: 404,500

spring:
  application:
    name: aries-base

#database
data-base-router:
  enabled: true
  single:
  - driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.163.100:3306/aries?useUnicode=true&characterEncoding=utf8
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:com/cf/aries/base/dao/*.xml
  type-aliases-package: com.cf.aries.common.po
  config-location: classpath:mybatis-config.xml
